apiVersion: v1
kind: Secret
metadata:
  name: minio-kserve-secret
  namespace: kserve-test
  annotations:
    serving.kserve.io/s3-endpoint: "localhost:9000"  
    serving.kserve.io/s3-usehttps: "0"   
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-minio-kserve
  namespace: kserve-test
secrets:
- name: minio-kserve-secret